version: 2.1
jobs:
  test:
    docker:
      - image: python:3.10.13
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: python3 flaskapp/test.py 
workflows:
  example:
    jobs:
      - test