version: 2.1
jobs:
  test:
    docker:
      - image: python:3.10.13
    steps:
      - checkout
      - run:
            name: Show Welcome
            command: echo "Bienvenidos a circle CI"
      - run:
            name: Run tests
            command: python3 flaskapp/test.py 
workflows:
  example:
    jobs:
      - test