version: 2.1
jobs:
    test:
        docker:
            - image: python:3.10.13
        steps:
            - checkout
            - run:
                name: Show version
                command: python3 --version
            - run:
                name: Run tests
                command: python3 flaskapp/test.py 
    build:
        docker:
            - image: cimg/base:2022.09
        steps:
            - checkout
            - run:
                name: Show version
                command: echo "hola"

workflows:
    example:
        jobs:
            - test:
                filters:
                    branches:
                      only:
                        - main
            - build